/**
 * IT Asset Catalog — Device Models & Specifications
 * Source: Asset inventory list (2026)
 * Format: assetCatalog[] — device model definitions (not individual deployed units)
 */

const assetCatalog = [
  {
    id: 'AST-001',
    type: 'Laptop',
    brand: 'Dell',
    model: 'Latitude 34xx (16GB)',
    spec: 'Intel i5, 16GB RAM, 512GB SSD, 14"',
    user: '',
    dept: 'IT',
    location: 'IT Storeroom',
    status: 'Available',
    serial: 'SN-DL34-001',
    warranty: '2027-12-31',
  },
  {
    id: 'AST-002',
    type: 'Laptop',
    brand: 'Dell',
    model: 'Latitude 54xx (16GB)',
    spec: 'Intel i7, 16GB RAM, 512GB SSD, 14"',
    user: '',
    dept: 'IT',
    location: 'IT Storeroom',
    status: 'Available',
    serial: 'SN-DL54-001',
    warranty: '2027-12-31',
  },
  {
    id: 'AST-003',
    type: 'Desktop',
    brand: 'Dell',
    model: 'OptiPlex 70xx (Low B)',
    spec: 'Intel i5 (6 core), 16GB RAM, 512GB SSD, Intel Integrated Graphics',
    user: '',
    dept: 'IT',
    location: 'IT Storeroom',
    status: 'Available',
    serial: 'SN-OP70LB-001',
    warranty: '2026-12-31',
  },
  {
    id: 'AST-004',
    type: 'Desktop',
    brand: 'Dell',
    model: 'OptiPlex 70xx (High)',
    spec: 'Intel i7 (8 core), 16GB RAM, 512GB SSD, AMD Radeon RX 640',
    user: '',
    dept: 'IT',
    location: 'IT Storeroom',
    status: 'Available',
    serial: 'SN-OP70H-001',
    warranty: '2026-12-31',
  },
  {
    id: 'AST-005',
    type: 'Desktop',
    brand: 'Dell',
    model: 'OptiPlex 70xx (High) (Upgrade 32GB RAM)',
    spec: 'Intel i7 (8 core), 32GB RAM (2x16GB), 512GB SSD, AMD Radeon RX 641',
    user: '',
    dept: 'Engineering',
    location: 'HQ F3',
    status: 'Available',
    serial: 'SN-OP70HU-001',
    warranty: '2026-12-31',
  },
  {
    id: 'AST-006',
    type: 'Desktop',
    brand: 'Dell',
    model: 'Precision T36xx (Low)',
    spec: 'Intel i7, 32GB RAM, 512GB SSD, 2TB HDD, Nvidia GeForce RTX 2060 Super',
    user: '',
    dept: 'Engineering',
    location: 'HQ F3',
    status: 'Available',
    serial: 'SN-DPT36L-001',
    warranty: '2027-06-30',
  },
  {
    id: 'AST-007',
    type: 'Desktop',
    brand: 'Dell',
    model: 'Precision T3680',
    spec: 'Intel i7, 32GB RAM, 512GB SSD, 2TB HDD, Nvidia GeForce RTX 4060',
    user: '',
    dept: 'Engineering',
    location: 'HQ F3',
    status: 'Available',
    serial: 'SN-DPT3680-001',
    warranty: '2027-06-30',
  },
  {
    id: 'AST-008',
    type: 'Desktop',
    brand: 'Dell',
    model: 'Pro Max Tower T2 (Low)',
    spec: 'Intel Ultra 7 265, 32GB RAM, 512GB SSD, 2TB HDD, Nvidia GeForce RTX 5070',
    user: '',
    dept: 'Engineering',
    location: 'HQ F3',
    status: 'Available',
    serial: 'SN-DPMT2L-001',
    warranty: '2028-12-31',
  },
  {
    id: 'AST-009',
    type: 'Laptop',
    brand: 'Apple',
    model: '14" MacBook Pro M4 Pro (24G/512GB)',
    spec: 'Apple M4 Pro chip, 12-core CPU, 16-core GPU, 16-core Neural Engine, 24GB RAM, 512GB SSD',
    user: '',
    dept: 'Engineering',
    location: 'HQ F3',
    status: 'Available',
    serial: 'SN-MBP14M4P-001',
    warranty: '2028-01-01',
  },
  {
    id: 'AST-010',
    type: 'Desktop',
    brand: 'Dell',
    model: 'Pro Max Tower T2 (High)',
    spec: 'Intel Ultra 7 265, 64GB RAM, 512GB SSD, 4TB HDD, Nvidia GeForce RTX 5070',
    user: '',
    dept: 'Engineering',
    location: 'HQ F3',
    status: 'Available',
    serial: 'SN-DPMT2H-001',
    warranty: '2028-12-31',
  },
  {
    id: 'AST-011',
    type: 'Laptop',
    brand: 'Apple',
    model: '13" MacBook Air M4 (16G/512GB)',
    spec: 'Apple M4 chip, 10-core CPU, 10-core GPU, 16-core Neural Engine, 16GB RAM, 512GB SSD',
    user: '',
    dept: 'IT',
    location: 'IT Storeroom',
    status: 'Available',
    serial: 'SN-MBA13M4-001',
    warranty: '2028-01-01',
  },
  {
    id: 'AST-012',
    type: 'Laptop',
    brand: 'Apple',
    model: '14" MacBook Pro M4 (24G/512GB)',
    spec: 'Apple M4 Pro chip, 12-core CPU, 16-core GPU, 16-core Neural Engine, 24GB RAM, 512GB SSD',
    user: '',
    dept: 'Engineering',
    location: 'HQ F3',
    status: 'Available',
    serial: 'SN-MBP14M4-001',
    warranty: '2028-01-01',
  },
  {
    id: 'AST-013',
    type: 'Laptop',
    brand: 'Apple',
    model: 'MacBook Pro M1',
    spec: 'Apple M1 chip, 8-core CPU, 8-core GPU, 16GB RAM, 512GB SSD, 14"',
    user: '',
    dept: 'IT',
    location: 'IT Storeroom',
    status: 'Available',
    serial: 'SN-MBPM1-001',
    warranty: '2025-12-31',
  },
  {
    id: 'AST-014',
    type: 'Laptop',
    brand: 'Dell',
    model: 'Pro 14 Core 5',
    spec: 'Intel Core 5 220U, 16GB RAM, 512GB SSD, 14"',
    user: '',
    dept: 'IT',
    location: 'IT Storeroom',
    status: 'Available',
    serial: 'SN-DPR14C5-001',
    warranty: '2027-12-31',
  },
  {
    id: 'AST-015',
    type: 'Laptop',
    brand: 'Dell',
    model: 'Pro 14 Ultra 7',
    spec: 'Intel Ultra 7 265U, 16GB RAM, 512GB SSD, 14"',
    user: '',
    dept: 'IT',
    location: 'IT Storeroom',
    status: 'Available',
    serial: 'SN-DPR14U7-001',
    warranty: '2027-12-31',
  },
  {
    id: 'AST-016',
    type: 'Laptop',
    brand: 'Dell',
    model: 'Pro Slim (High)',
    spec: 'Intel Core Ultra 7, 32GB RAM, 512GB SSD',
    user: '',
    dept: 'IT',
    location: 'IT Storeroom',
    status: 'Available',
    serial: 'SN-DPSLIMH-001',
    warranty: '2027-12-31',
  },
  {
    id: 'AST-017',
    type: 'Laptop',
    brand: 'Dell',
    model: 'Pro Slim',
    spec: 'Intel Core Ultra 7, 16GB RAM, 512GB SSD',
    user: '',
    dept: 'IT',
    location: 'IT Storeroom',
    status: 'Available',
    serial: 'SN-DPSLIM-001',
    warranty: '2027-12-31',
  },
];
